### ISSUE TITLE
Default ordering in dispatch queue should be most recent first

### ISSUE THREAD

**Issue by wsanchez** [burningmantech/ranger-ims-server#102]
Default ordering in dispatch queue should be most recent first

**Comment by wsanchez** [comment]
cc @kimballa

**Comment by wsanchez** [comment]
I went with a default ordering of:
 * priority ascending
 * created descending

So, high priority items first, and within a priority the most recent comes first.

7c56acd3e9f5e61c07072abdf0917b96675c157a

**Comment by kimballa** [comment]
Thanks!
