### ISSUE TITLE
Use a combobox for rangers and incident types so typing works better

### ISSUE THREAD

**Issue by wsanchez** [burningmantech/ranger-ims-server#107]
Use a combobox for rangers and incident types so typing works better

**Comment by wsanchez** [comment]
@kimballa suggests https://jqueryui.com/resources/demos/autocomplete/combobox.html

**Comment by kimballa** [comment]
Disclaimer: that was the first result in google. And jquery is, generally, a well-supported / standard practice in JS development. But I've never used it, and "suggests" might be more credence than it's worth :) I suggested it mostly in terms of inspiration/example, not a pre-validated implementation

**Comment by kimballa** [comment]
But, +1 for this feature!

**Comment by wsanchez** [comment]
This looks promising: https://github.com/danielfarrell/bootstrap-combobox
Example/demo: http://formvalidation.io/examples/bootstrap-combobox/

**Comment by prqpn** [comment]
this is also very challenging to use on mobile

**Comment by srabraham** [comment]
I effectively did this recently for "add ranger". I could do it for incident type too. https://github.com/burningmantech/ranger-ims-server/pull/1292
