### ISSUE TITLE
using dropdown fields creates several new incidents

### ISSUE THREAD

**Issue by kimballa** [burningmantech/ranger-ims-server#117]
If you start on a new incident tab by manipulating the fields for location, etc (as opposed to starting with "summary"), then it creates a new incident for each manipulation. i.e., scrolling through 01->02->03->04:00 will create four incidents with blank summaries.

**Comment by wsanchez** [comment]
That sounds bad

**Comment by wsanchez** [comment]
Right now, editing those don't seem to do anything at all, and makes the page stop handling edits: #176

I bet that with the new underlying data store code, we're just seeing a different effect from the same root cause.

**Comment by wsanchez** [comment]
OK the version of this problem that happened last year is no longer a thing, so I'm going to close this in favor of #176.
