### ISSUE TITLE
dropdown for ranger names is very difficult to use

### ISSUE THREAD

**Issue by kimballa** [burningmantech/ranger-ims-server#118]
On "large" data issues (e.g., see #326 in 2016) using the dropdown gets slow and the UI is unresponsive.

Moreover, the ability to navigate a dropdown of over 700 names is incredibly difficult and slow; this is very hard to keep up with radio traffic.

**Comment by wsanchez** [comment]
Two things:
 * The list should only include on-site Rangers.
 * Some auto-complete thing could be better than drop-downs

**Comment by wsanchez** [comment]
dup of #107
