### ISSUE TITLE
time code of "GMT - 0700" is confusing UI to operators

### ISSUE THREAD

**Issue by kimballa** [burningmantech/ranger-ims-server#120]
Some operators were convinced that the times were really in GMT and they had to do the math in their head. If "GMT - 0700" could be replaced with "PDT" or some other more friendly time code, that would be better UX

**Comment by kimballa** [comment]
this refers to times in the event log. The "- 0700" part was lost.

**Comment by wsanchez** [comment]
Changing it to

```javascript
date.format("MMMM Do YYYY HH:mm:ss")
```

renders as: 

```
August 9th 2018 17:35:14, Tool:
```

**Comment by wsanchez** [comment]
If the local TZ adds awesome: https://momentjs.com/timezone/docs/
But adding another module for that seems meh right now.
