### ISSUE TITLE
HTTP path for IMS availability

### ISSUE THREAD

**Issue by wgjohnson** [burningmantech/ranger-ims-server#128]
Is there a path on IMS to test availability of the service without mimicking a user? We (Secundus & El Weso) are developing a [program](https://github.com/wgjohnson/chooch) to get better answer to "why?" for issues like #124. 

For example, a URL like `http://rangerims.nv.burningman.org/ping` where we get a 200 from twisted, and (nice to have) a minimal metadata page for a sanity check of IMS without having to manipulate the DOM or create unnecessary load.

Optionally this is a good chance for you to say "[no](https://www.youtube.com/watch?v=WDgq-K2oYLo)" and chastise me for going off reservation. :)

**Comment by wsanchez** [comment]
Depends on what you are trying to measure.  If all you need is:
 * Server is responding to requests
 * Network latency plus time to process a simply request

Then just hit '/ims/', which will give you the home page and does not require auth.

Is that enough?

**Comment by wsanchez** [comment]
Actually, there is an explicit ping endpoint: `/ims/api/ping/`
