### ISSUE TITLE
Printing an IMS entry looks lame

### ISSUE THREAD

**Issue by wsanchez** [burningmantech/ranger-ims-server#130]
Phil says printing an IMS entry doesn't work well:

 * The “Summary” field and “Location” “Name” fields get cut off.
 * Despite the checkbox option for “show history” being unchecked (i.e., to eliminate clutter), you still get full details (i.e., clutter).

Bonus request:
 * (An enhancement) It would be good to make the html title be “Ranger YYYY IMS” before the incident #, where YYYY is the four-digit year.  This way you avoid any confusion in the filename (“Save as…”) as to which year this incident # is for.  (The filename in save-as is imputed from the title.)

**Comment by srabraham** [comment]
Printouts now look much better: https://github.com/burningmantech/ranger-ims-server/pull/1382
