### ISSUE TITLE
Backend: Use first incident entry first line as summary when no summary is provided (have server do this, rather than client)

### ISSUE THREAD

**Issue by srabraham** [burningmantech/ranger-ims-server#1325]
Incident's summary field can be null, if no user sets that field. That makes sense for a new incident. After a user adds an entry to that incident, the frontend starts using that entry's text as though it were the summary. It's never actually updated as such in the backend though.

For example, if I make a new incident without a summary

<img width="315" alt="image" src="https://github.com/user-attachments/assets/2597d214-95b1-4d1b-8b1c-aaaec0810e95">

Then add an entry to it

<img width="506" alt="image" src="https://github.com/user-attachments/assets/cbeccf72-06bd-4695-8daf-7efced57468e">

I then see the following on the incident page. Note that the grayed text is a placeholder, filled in on the client-side.

<img width="538" alt="image" src="https://github.com/user-attachments/assets/a603ae99-1a4a-4b75-acdb-5c47d0489077">

Similarly I see this on the incidents table, and here too, that string is pulled off the first incident entry by the client code. That string does not exist in the database as a summary; it's still null over there.

<img width="745" alt="image" src="https://github.com/user-attachments/assets/a69df468-9ec8-4b54-9aee-f2ef53d036f4">

I suggest that we consider actually just populating the summary field in this situation, pushing that first detail entry's text to the server and into the DB. That has a few benefits:
1. It would simplify client code in both the old and new web clients, removing this special case computation of the summary (on the incident and the incidents pages). See [here](https://github.com/burningmantech/ranger-ims-server/blob/65c0c663e8fadb3e967f8b467fcb415f3cb1b184/src/ims/element/static/incident.js#L506-L508), [here](https://github.com/burningmantech/ranger-ims-server/blob/65c0c663e8fadb3e967f8b467fcb415f3cb1b184/src/ims/element/static/incident_report.js#L179-L181), and [especially here](https://github.com/burningmantech/ranger-ims-server/blob/65c0c663e8fadb3e967f8b467fcb415f3cb1b184/src/ims/element/static/ims.js#L400-L422)
2. It would allow us to better optimize the incidents API (https://github.com/burningmantech/ranger-ims-server/issues/1324). Currently the incidents page needs to look up all the INCIDENT__REPORT_ENTRYs, just in case the client has to populate the placeholder summary field.

FYI @wsanchez

**Comment by wsanchez** [comment]
I disagree… There's a difference between data a user put in and data that gets generated, and this makes that distinction go away. We should be able to optimize that query better if needed.

**Comment by srabraham** [comment]
I'm mostly not liking that this is a subtle client-side feature. I'd expect that if I call the API to fetch an incident, I should get back the same summary value as I see in the UI. Instead, it can show up in the UI, but be null in the API.

I don't have strong feelings about this though.
