### ISSUE TITLE
EventSource times out at 100 seconds for AWS-hosted IMS

### ISSUE THREAD

**Issue by srabraham** [burningmantech/ranger-ims-server#1364]
Requests to our AWS-hosted IMS instances go through CloudFlare. CloudFlare times out an HTTP connection after 100 seconds of inactivity, with a 524 error code. ([See here](https://community.cloudflare.com/t/default-timeout-limit-increase/240042)). 

This is a nuisance for the EventSource endpoint, in which the client expects the connection to open and stay open to keep being sent new events from the server.

This is somewhat unimportant, since IMS runs on-playa for the time of year when it matters. If we wanted to do something about this though, within the confines of that 100 second limit, we could have the client JS code do a reconnect on a 524 error code.

Anyway, @wsanchez, I'm curious for any thoughts on this. I can imagine that people would notice this issue during Operator or Command training, but probably not anytime else. I don't like that it might reduce users' confidence in the auto-updating though.

(Note that my recent change to use a Broadcast Channel actually makes this situation a tiny bit better, because it at least keeps the tabs in sync to events, and if all prior EventSource connections have 524'ed, then opening a new tab will acquire a new EventSource connection for all those tabs to share)

**Comment by mikeburg** [comment]
This [article](https://medium.com/@imrockpan/remember-the-problems-encountered-when-deploying-sse-message-push-to-cloudflare-c3506c42e9e2) has a suggestion on how to handle the issue.

The TL;DR is send a 'X-Accel-Buffering: no' HTTP header, and to send a keep alive message every 30 seconds.

**Comment by srabraham** [comment]
Ahhh, good find. Yeah, I haven't seen the Nginx problem this references, so the X-Accel-Buffering tweak may not be needed? Keep-alive events would solve the 100 second Cloudflare timeout though! Thanks!

**Comment by srabraham** [comment]
Yeah, something silly like this should work. I'm not sure of how Twisted's concurrency model works though (e.g. would this need a mutex), and this may not be the prettiest place to put/write the code. I could use @wsanchez 's input. (Also, sorry for the large number of pings today, Tool!)

```patch
diff --git a/src/ims/application/_eventsource.py b/src/ims/application/_eventsource.py
index e767dbb4..3ab2ca6c 100644
--- a/src/ims/application/_eventsource.py
+++ b/src/ims/application/_eventsource.py
@@ -24,6 +24,7 @@ from time import time
 from typing import Any, ClassVar, Deque

 from attrs import field, frozen
+from twisted.internet.task import LoopingCall
 from twisted.logger import ILogObserver, Logger
 from twisted.web.iweb import IRequest
 from zope.interface import implementer
@@ -82,6 +83,15 @@ class DataStoreEventSourceLogObserver:
     _start: float = field(init=False, factory=time)
     _counter: list[int] = field(init=False, factory=lambda: [0])

+    # it's misleading that this is a list...
+    # really just one LoopingCall is made, but fields in this class are all frozen,
+    # so we couldn't set to None and initialize later
+    _loopers: list[LoopingCall] = field(init=False, factory=list)
+
+    def _publishKeepAlive(self):
+        self._publish(Event(
+            eventID="none",
+            eventClass=str.__name__,
+            message="wake up!",
+        ), "none")
+
     def addListener(
         self, listener: IRequest, lastEventID: str | None = None
     ) -> None:
@@ -94,6 +104,15 @@ class DataStoreEventSourceLogObserver:

         self._listeners.append(listener)

+        if not self._loopers:
+            looper = LoopingCall(self._publishKeepAlive)
+            self._loopers.append(looper)
+            self._log.info("creating looper")
+        if not self._loopers[0].running:
+            self._log.info("starting looper")
+            # fire every 90 seconds
+            self._loopers[0].start(90.0)
+
+
     def removeListener(self, listener: IRequest) -> None:
         """
         Remove a listener.
@@ -102,6 +121,11 @@ class DataStoreEventSourceLogObserver:

         self._listeners.remove(listener)

+        if not self._listeners and self._loopers:
+            if self._loopers[0].running:
+                self._log.info("stopping looper")
+                self._loopers[0].stop()
+
     def _transmogrify(
         self, loggerEvent: Mapping[str, Any], eventID: int
     ) -> Event | None:
```

**Comment by srabraham** [comment]
I went with the client-side approach, in which I just have the tab try forever to reconnect via EventSource anytime the connection closes
