### ISSUE TITLE
Cannot create new incident from start page; can modify existing records

### ISSUE THREAD

**Issue by vought** [burningmantech/ranger-ims-server#163]
To reproduce:

1. in Safari 10.x, Click 'Test' database, and pick 'New' to create an incident report. 
2. Type a summary of the incident.
3. Press the Tab key.

The remote file lscache.js does not load and causes an
![screen shot 2017-08-07 at 3 19 53 pm](https://user-images.githubusercontent.com/7526256/29048162-2a01c864-7b84-11e7-87a7-15369256416a.png)
 error when creating the new incident by tabbing from the summary field:
```
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (lscache.min.js, line 0)
[Error] ReferenceError: Can't find variable: lscache
	localLoadPersonnel (incident.js:245)
	loadPersonnelAndCache (incident.js:184)
	loadedIncident (incident.js:23)
	loaded (incident.js:156)
	ok (incident.js:115)
	loadIncident (incident.js:127)
	loadAndDisplayIncident (incident.js:160)
	loadedBody (incident.js:40)
	complete (ims.js:251)
	(anonymous function) (jquery.min.js:4:19046)
	each (jquery.min.js:2:2820)
	(anonymous function) (jquery.min.js:4:19027)
	i (jquery.min.js:2:27609)
	fireWith (jquery.min.js:2:28371)
	A (jquery.min.js:4:13870)
	(anonymous function) (jquery.min.js:4:16148)
[Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (incidents, line 0)
```
The same user is able to modify existing incidents already in the test database.

**Comment by bndoug** [comment]
This error occurs in Safari 10.x and Chrome Version 59.0.3071.115 (Official Build) (64-bit). Probably in Firefox too, but nobody uses that anymore.

**Comment by wsanchez** [comment]
blimey! you got me right away 😢

**Comment by wsanchez** [comment]
OK, I think what was going on here is that I didn't include the OpenSSL, so it failed at downloading and caching some jquery nonsense it uses.

Fixed: https://github.com/burningmantech/ranger-ims-server/commit/8793b39b05271fb0a1665f555b592e327973a716

Deployed, please try again.

**Comment by bndoug** [comment]
I can now access the dropdown lists; they're populated, which wasn't happening before. Unfortunately, attempts to create information in any field of a new incident still results in a 500 Internal Server Error. It's as if I don't have permission to add new information.

```Request: {"location":{"name":"Tokyo","type":"garett"},"state":"new","priority":3}

Response: Failed to load resource: the server responded with a status of 500 (Internal Server Error)
```

**Comment by bndoug** [comment]
Additional info from the Safari log:
```
Attempted to add a new incident title: 

[Log] Failed to apply edit: (incident.js, line 872)
Internal Server Error

[Log] Event listener error (ims.js, line 777)

Tried to add a Ranger name:

[Log] Failed to apply edit: (incident.js, line 872)
Internal Server Error


Tried to add a location:

[Log] Failed to apply edit: (incident.js, line 872)
Internal Server Error

```

**Comment by wsanchez** [comment]
OK thanks

**Comment by wsanchez** [comment]
OK I think you are running into #169 and #171.

**Comment by wsanchez** [comment]
Both are merged and deployed.

Try again.  Please note #176: Some fields in new incident page don't work

**Comment by vought** [comment]
Creating new cases in the test database now works correctly; see incident #123 in the test db.
