### ISSUE TITLE
Sorting by created date doesn't appear to work

### ISSUE THREAD

**Issue by vought** [burningmantech/ranger-ims-server#177]
In queue view, Clicking on the Created header does not sort incidents by their creation date. Other header sorts appear to work properly.

To reproduce:
1. In queue view, set the filters to Show All, Show All Days, and Show 100 Rows.
2. Click the 'Created' header to sort the cases shown. 

Expected result: Incidents should sort by date created, summary title, or Location.
Actual result: No sorting of the list shown takes place. 

Impact: May be tough to see recent incidents easily.

**Comment by wsanchez** [comment]
dup: #81
