### ISSUE TITLE
Incidents By Type report

### ISSUE THREAD

**Issue by wsanchez** [burningmantech/ranger-ims-server#264]

**Comment by srabraham** [comment]
@wsanchez I think it would be fairly easy to add filtering on the incidents table based on incident type (I have it kind-of working locally). I suspect people would find this useful, and that it would give more value to Incident Types as a whole.

<img width="514" alt="image" src="https://github.com/user-attachments/assets/818d2971-511b-4e2e-8883-9ac0fdb85798">

**Comment by srabraham** [comment]
Done, I suppose? It's not a "report", but it's probably good enough. The incidents table can be printed to paper/pdf, as needed
