### ISSUE TITLE
Lost report entry when closing the window

### ISSUE THREAD

**Issue by wsanchez** [burningmantech/ranger-ims-server#279]
If we have text in the new report entry field, that data will be tossed when user closes the window if she doesn't save the entry first.  We suspect that this is the cause of #263.

Other fields auto-save to the server, so it is not unreasonable for a user to expect that to be the case here, especially new users, which tends to be the case for those writing incident reports.

We should be able to prevent this my using some JavaScript-fu to capture the window close event and either bring up an "are you sure?" dialog or simply save the text on close.

I think that a dialog is probably more appropriate, since the text might be garbage or incomplete; perhaps the user just forgot there was text there at all (and didn't just forget to save it first).

**Comment by wsanchez** [comment]
@kimballa Thoughts welcome on the dialog vs. "just save" options.

**Comment by kimballa** [comment]
Hm. Lots of folks on the team are incredibly computer un-savvy, and likely won't bother to type out a report twice if it got lost by accident. Many modern web apps (e.g. Google Docs) auto-save, with no expectation of a specific button being required for entry. Given that the Incident Report screen is used most by dirt rangers -- not trained operators -- I vote that we should go for the lowest-friction option for them. i.e., just save the text in the `onBlur` event for the textarea. 

The "risk" of this is that we get a pile of incomplete or erroneous reports for the operator to deal with. The operators need to spend some time at end of shift linking Incident Reports to IMS tickets anyway; and the load is not so great -- usually just 2 or 3; 6 on a busy shift. So, I think that so long as the operator has an easy-to-use "dismiss"/"delete"/"archive" button that can clear those out, it's not too much further administrative burden to deal with half-completed reports.
