### ISSUE TITLE
IMS web client limited to six open tabs

### ISSUE THREAD

**Issue by kimballa** [burningmantech/ranger-ims-server#281]
When dealing with a busy shift, you need a tab open for the main incident list, a blank incident "hot" to start typing in, and you may be tracking several long-running incidents (so you can update status from "dispatched" to "on scene", etc). You may want a second incident list open with some filters attached too. (e.g., your default incident list for open/on-hold, and use a second one to run a search for a prior incident for khaki.)

The web browser only allows a given domain to have six open sockets to the backend site.  The result being, if you try to open additional tabs in the same domain (e.g. `rangerims.nv.burningman.org` or wherever it is that the live site is), they'll spin in the loading state indefinitely until you close another issue. It's very easy to bump up against this limit.

The fix is probably relatively complicated, since it requires client-side state-pooling of the socket(s) back to the backend and then multiplexing requests/responses over the socket and demuxing them based on which window they're associated with... so I realize it's not a simple ask. But it would make the operator interface much more powerful.

**Comment by kimballa** [comment]
(n.b., if there's an IT administrative fix, like somehow configuring the browser to increase its per-domain socket limit to something more like 30, that might solve this client-side without any code. Dunno if that's possible.)

**Comment by wsanchez** [comment]
This is very interesting.  I had no idea.

**Comment by corprew** [comment]
> The fix is probably relatively complicated

the laziest way to fix this is to make all the operator stations use firefox and set the about:config value `network.http.max-persistent-connections-per-server` to something as high as seems useful.  I've had to implement solutions for this in the past so lmk if you'd like some more complex ones.

**Comment by kimballa** [comment]
I'm not opposed to using firefox...

**Comment by wsanchez** [comment]
FYI, the web client uses HTML5 EventSource, which is causes each tab to hold a connection to the server to get updates.

So a better solution is something that can be shared across tab/window contexts; we really should only need one such listener.

**Comment by srabraham** [comment]
How valuable of a feature is it for IMS to hold connection to automatically get updates? Would users be opposed to refreshing, or perhaps to opting in to auto-refresh, rather than having it on by default?

**Comment by kimballa** [comment]
Now that you mention it, I think there was a regression in the system this year -- or maybe the system is simply not resilient enough to the sometimes-flaky internet in BRC -- but I felt like I had to manually refresh many (most? all?) the time to ensure I had the latest content. I no longer rely on auto-sync.

This would all be mitigated if the "collection"-oriented incident metadata (rangers involved; incident types) had `POST`/`PATCH` endpoints that added or removed a single list item rather than push the entire list as the client sees it to the server to overwrite the list that was already there. It's currently frustratingly easy for me to add `Bucket` to the rangers involved, and then another operator tries to add `Hubcap`, but since they did not see my action first, my partner pushed `["Hubcap"]` to the field which clobbered the `["Bucket"]` already in there, rather than appending `["Bucket", "Hubcap"]` like you would expect. The same "diff-oriented" behavior for removing rangers/incident types would also make it more resilient. 

To the extent that the sync behavior is being redone, though, using a single `ServiceWorker` for the domain would alleviate these bottleneck issues.

**Comment by mikeburg** [comment]
The EventSource connection limit is based off what protocol was used to open the connection. For HTTP/1.0, it's 6 connections. For HTTP/2.0, it's a 100.  This might require some poking at the nginx configuration file to verify the connection is happening over HTTP/2.0.
