### ISSUE TITLE
Consider alternate issue type for "Sexual Assault"

### ISSUE THREAD

**Issue by kimballa** [burningmantech/ranger-ims-server#292]
The IMS has an issue type for `"Assault/Sexual"`, but recent Ranger protocol dictates that the correct formulation for a radio report is "Sexual Violence," not "Sexual Assault," and that Khaki should not use the words "Sexual Assault" on the radio.

Should we relabel this issue type to `"Sexual Violence"` for consistency?

**Comment by wsanchez** [comment]
yes, that's the plan
