### ISSUE TITLE
Clicking links to create a new incident report cause "Permission Denied"

### ISSUE THREAD

**Issue by kimballa** [burningmantech/ranger-ims-server#297]
From Ranger Virtual:

> Operator leads, Virtual.
> 
> While playing around in the IMS linked from the online training, I found a "permission denied" link when attempting to load the incident reports page.
> 
> https://ims.example.com/ims/app/incident_reports/
> 
> Is there a ticky-box I'm missing or is this something bigger?
> 

I have confirmed that I see the same behavior

Steps to reproduce:
* Go to  https://ims.example.com/ims/app/ 
* Log in
* Click "New Incident Report"
* See `permission denied`

Alternate reproduce path:
* Log in as before
* Explicitly select the "Test" event >  sends you to  https://ims.example.com/ims/app/events/Test/queue
* Click the red notepad icon in the upper left corner > sends you to  https://ims.example.com/ims/app/incident_reports/
* ... which says `Permission denied`

I think that some of the links are not updated to reflect your recent schema change that associates untagged incident reports with a particular event.

**Comment by wsanchez** [comment]
Should work on new staging server, though the workflow is a bit different.
