### ISSUE TITLE
Staging server has MySQL connection error

### ISSUE THREAD

**Issue by kimballa** [burningmantech/ranger-ims-server#298]
I logged into the staging server and attempted to select the event from the upper left.

I got a stack trace render instead:
![mysql-err](https://user-images.githubusercontent.com/87376/63207864-6ab46700-c082-11e9-8bb2-2c0ac3d5e721.png)

**Comment by wsanchez** [comment]
Huh.  Why an app running in AWS would have a timeout talking to a database on the same AWS VPC confuses me.

**Comment by wsanchez** [comment]
OK looks like the problem is probably that idle connections go funny:

https://stackoverflow.com/questions/47711689/error-while-using-pymysql-in-flask

**Comment by wsanchez** [comment]
@kimballa Try now. new code deployed.

**Comment by kimballa** [comment]
@wsanchez , I no longer experience the explicit MySQL error. However, I see no events in the Event list after I log in. Is that expected behavior?

![empty-list](https://user-images.githubusercontent.com/87376/63232213-934f7480-c1da-11e9-9e65-d62618c2d9e1.png)
