### ISSUE TITLE
System entries sometimes show nerd values

### ISSUE THREAD

**Issue by wsanchez** [burningmantech/ranger-ims-server#30]
When changes are made, a system entry is created describing the change.

Some new values are described using an underlying constant instead of the corresponding descriptive string.

**Comment by wsanchez** [comment]
Changed concentric streets are being shown as their ID instead of by name.
`editIncident()` is going to need more context to map ID to name, because that changes by year.

**Comment by wsanchez** [comment]
Which makes me wonder is system entries are perhaps better stored as data instead of strings, and the clients should deal with making that presentable.

**Comment by wsanchez** [comment]
Or events objects can be passed to the store, which could asked for things like street names, as long as the store is logging changes as rendered text, which is suboptimal, but the status quo.

**Comment by wsanchez** [comment]
#109 for creating the event object in the model

**Comment by wsanchez** [comment]
#109 is done… need to hang street info off if it

**Comment by srabraham** [comment]
System entries seem to be in a pretty good state. Close?
