### ISSUE TITLE
request: improve contrast of light mode theme

### ISSUE THREAD

**Issue by kimballa** [burningmantech/ranger-ims-server#322]
Given the amount of glare on monitors, the khaki-monotone theme gets very washed out. Higher contrast text and textboxes would improve daytime readability.

**Comment by wsanchez** [comment]
What khaki?

IMS is black text on a white background.  Black on white is about as high contrast as one can get.

**Comment by kimballa** [comment]
Ranger Coal Smoke has more details on this one. If he's not already added to this repo / issue tracker, it would be helpful if he could be so he can speak directly here.

**Comment by mikeburg** [comment]
@kimballa The Clubhouse uses a khaki color theme - perhaps this is really a Clubhouse issue and not an IMS issue?

**Comment by wsanchez** [comment]
That seems more likely to me.
