### ISSUE TITLE
Rename Incident Reports (IRs) to Field Reports (FRs)

### ISSUE THREAD

**Issue by virtual256** [burningmantech/ranger-ims-server#371]
While Operating, I have had multiple times where a ranger would come up to the window and ask for an "incident number" in an unclear fashion.  This was either asking for the IMS number for something or talking about a previous report they had submitted.  The moment of confusion is something we can mitigate by changing the name to be something clearly distinct.

I propose using "Field incident reports" (FIRs) instead, in all places that they are referenced - the Ranger accessible page to generate them, the IMS entries themselves, and the backend list of FIRs themselves.

**Comment by virtual256** [comment]
Related to this, having the number itself be "FIR-0001" will further differentiate from "IMS-0123" style numbers.

**Comment by wsanchez** [comment]
@virtual256 I myself have been challenged by the similarity and had been at a loss for a better name, but I like your suggestion.

How do we feel about shorting that to "field report", which makes it a little more distinct as well as shorter?

**Comment by virtual256** [comment]
Taking out the overlapping "I" feels like a plus.  I like it.

**Comment by kimballa** [comment]
+1!

**Comment by srabraham** [comment]
As a first step, we could just do the rename in user-facing client code (i.e. just a few places in html templates and JS). That'd be easy, and wouldn't be as risky as relocating APIs, doing various DB migrations, and updating lots of Python.

**Comment by kimballa** [comment]
That would definitely be a big improvement, and accomplishes what I care
about most!

**Comment by srabraham** [comment]
@kimballa @wsanchez I'm doing the aforementioned surface-level tweaks now. One question for both of you: are we good to standardize on "IMS #" for incidents and "FR #" for field reports? We don't actually have those initialisms in the system now, but they seem like the most reasonable choices.

**Comment by virtual256** [comment]
That language is perfect, thank you.

**Comment by srabraham** [comment]
Note to self: we'll need to update various documentation in response to this change

**Comment by srabraham** [comment]
> Note to self: we'll need to update various documentation in response to this change

I put in a request in "The ART of Incident Reporting" Google Doc, owned by Easy E, to update all references there from "Incident Report" to "Field Report".
