### ISSUE TITLE
Allow login for non-Rangers

### ISSUE THREAD

**Issue by wsanchez** [burningmantech/ranger-ims-server#38]
Some non-Ranger persons should be able to access the IMS, eg.:
 - ESD Dispatch
 - Chaz
 - Roger

**Comment by wsanchez** [comment]
We have non-Rangers accounts in the Clubhouse, but I don't think this sort of use case was considered, so… hey @flwyd @plapsley might that work?

**Comment by plapsley** [comment]
Yeah, this is easy-peasy.  We can create them as "auditors" and then we can remove even the ability for them to log in to the Clubhouse (so they can't spy on our schedules and stuff).  Nice!

**Comment by wsanchez** [comment]
OK great, will follow up in email

**Comment by wsanchez** [comment]
OK this works.
