### ISSUE TITLE
Use EventSource to push updates to clients

### ISSUE THREAD

**Issue by wsanchez** [burningmantech/ranger-ims-server#46]
Use [EventSource](https://developer.mozilla.org/en-US/docs/Web/API/EventSource) to push updates to clients.

**Comment by wsanchez** [comment]
Things to potentially push updates for:
 * incidents
 * personnel
 * incident types
 * incident reports

**Comment by wsanchez** [comment]
No way this will get done in the next three weeks, so punting.

**Comment by wsanchez** [comment]
Server now has a URI for data updates as of 22d0102df1bce790d569b6a16863e15afdad9a77

**Comment by wsanchez** [comment]
Dispatch queue subscribes to those events: c7fbe38f0cca1c2d956e846338bc8e8becd8b260

This reloads the entire queue data set after any update, so one question is whether that scales OK.  It does appear that DataTables only does one GET request even though multiple update events come in, so that's a great thing.

**Comment by wsanchez** [comment]
Not done yet is having individual incident contexts update.

**Comment by wsanchez** [comment]
@kimballa: this is on the demo server.

Try opening the dispatch queue in one window, then open an incident in another.  Change the incident's state or some other data visible in the dispatch queue and it should automatically update in the queue.

**Comment by wsanchez** [comment]
#110 for incident pages
#111 for incident types
#112 for personnel
#113 for incident reports

**Comment by wsanchez** [comment]
Closing this bug since the main server side feature is is place.

**Comment by kimballa** [comment]
Hmm. Sorry for getting to this late; it was a busy weekend of packing.

This "sort of" works for me. Creating an incident in a new tab, I see it show up in the dispatch queue. I then changed the incident description and it didn't update (for at least 10 seconds).

I refreshed the dispatch queue and it appeared correctly. I then tried to repeat this process, and loaded another new incident tab. This new description is not present.

I do see the default sorting, and the new incident updating URL, so thanks for getting those in there.

**Comment by wsanchez** [comment]
Well, poop.  Chrome, right?

**Comment by kimballa** [comment]
da

**Comment by wsanchez** [comment]
OK I just pushed an update, though I don't think that should have fixed anything…

But I have Safari and Chrome open on my Mac and if I change an incident state or summary in Safari, I'm seeing the update in Chrome on both the Dispatch Queue and the open incident page (which this update added support for).

I've also tested updated coming to Safari.

Might need to debug non-Mac cases on site.

**Comment by kimballa** [comment]
Whether or not that should have fixed anything, I can no longer reproduce the failure. Looking good! 

¯\_(ツ)_/¯
