### ISSUE TITLE
k8 broke something but it's probably my fault

### ISSUE THREAD

**Issue by wsanchez** [burningmantech/ranger-ims-server#63]
Seen on demo server:
```
2016-06-23T16:17:23-0700 [twisted.python.log#info] "127.0.0.1" k8 - [23/Jun/2016:23:17:22 +0000] "POST /ims/Test/incidents/ HTTP/1.0" 500 15 "https://khaki-shack.prettyok.net/ims/Test/queue/incidents/new" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/8.0.7 Safari/600.7.12"
2016-06-23T16:17:39-0700 [ims.service.service.WebService#critical] Request failed

Traceback (most recent call last):
  File "/home/ims/ranger-ims-server/.develop/virtualenv/site-packages/twisted/internet/defer.py", line 1274, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
  File "/home/ims/ranger-ims-server/.develop/virtualenv/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/home/ims/ranger-ims-server/ims/service/klein.py", line 65, in wrapper
    response = yield f(self, request, *args, **kwargs)
  File "/home/ims/ranger-ims-server/.develop/virtualenv/site-packages/twisted/internet/defer.py", line 1274, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/home/ims/ranger-ims-server/.develop/virtualenv/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/home/ims/ranger-ims-server/ims/service/json.py", line 148, in newIncidentResource
    self.storage.createIncident(event, incident)
  File "/home/ims/ranger-ims-server/ims/store/sqlite.py", line 420, in createIncident
    incident.validate(noneNumber=True)
  File "/home/ims/ranger-ims-server/ims/data/model.py", line 326, in validate
    "location", self.location, Location, optional=True, recurse=True
  File "/home/ims/ranger-ims-server/ims/data/model.py", line 135, in _validateIsInstance
    obj.validate()
  File "/home/ims/ranger-ims-server/ims/data/model.py", line 630, in validate
    "address", self.address, Address, optional=True, recurse=True
  File "/home/ims/ranger-ims-server/ims/data/model.py", line 135, in _validateIsInstance
    obj.validate()
  File "/home/ims/ranger-ims-server/ims/data/model.py", line 840, in validate
    "concentric", self.concentric, int, optional=True
  File "/home/ims/ranger-ims-server/ims/data/model.py", line 139, in _validateIsInstance
    "{} must be a {}, not {!r}".format(name, typeSpec, obj)
ims.data.model.InvalidDataError: concentric must be a <type 'int'>, not u'0'
```

**Comment by wsanchez** [comment]
"I get this error when adding street location details"

Oh yeah, I see this traceback for radial hour and minute as well as concentric streets.  Someone needs to make a `unicode` into an `int`.  I blame `newIncidentResource`.

**Comment by wsanchez** [comment]
I wonder why it works when I do it… Now I blame k8.

**Comment by wsanchez** [comment]
Oh wait, has to be a new incident.  Huh.

**Comment by wsanchez** [comment]
No still works, still blaming k8

**Comment by wsanchez** [comment]
Breaks in SQL store, in line `420`.  *That's* suspicious, k8.

Hrm, Safari 8, I'm on 9.  k8 UPGRADE YOUR MAC ALREADY, GEEZ.  Maybe it's that? HOW DID YOU BREAK THIS k8?

**Comment by corprew** [comment]
I can replicate something that looks like this issue if I set the hour to '1' and then set it back to the blank hour.

Version 9.1.1 (11601.6.17)

**Comment by wsanchez** [comment]
Clue: some these string are zero-padded:
```
ims.data.model.InvalidDataError: radialHour must be a <type 'int'>, not u'06'
ims.data.model.InvalidDataError: radialMinute must be a <type 'int'>, not u'00'
ims.data.model.InvalidDataError: concentric must be a <type 'int'>, not u'0'
```
This surprises me.

**Comment by wsanchez** [comment]
No… that shouldn't surprise me.  The pop-ups uses padded strings.  What surprises me is that only k8 has breaking superpowers.

OK, the JavaScript that creates the JSON turd containing edits should be calling `Number.parseInt` on the radial address components.  So the JSON should contain an integer, which should be an `int` when we read it on the server, but somehow isn't.

Probably the sane thing to do is force values to `int` in the data model, in `RodGarettAddress`…  except boo.  Perhaps better is to do it when reading the JSON object, so it's only at that boundary.

**Comment by wsanchez** [comment]
Dammit Zeitgeist, that's a different bug.

**Comment by iamk8** [comment]
I like Safari 8 because it rhymes with my name. I'll update and try again.

I can also break it, but differently, in Chrome! You probably just saw that errror.

![image](https://cloud.githubusercontent.com/assets/4050290/16344790/4aa22740-39f3-11e6-9f90-8f39f272986d.png)

**Comment by wsanchez** [comment]
That one is #65

**Comment by wsanchez** [comment]
OK, the plan is to add a bunch of type checking to the JSON -> Incident thingo.

**Comment by wsanchez** [comment]
Fixed: 6a54c55afcdb4b83d5ab9e1aab173ca313201f7b

**Comment by wsanchez** [comment]
OK, I'm a lot stricter about types now.

@iamk8, any chance you can make this happen again?

It should give you an error again, but hopefully in a way that makes it clearer where it's coming from.

**Comment by iamk8** [comment]
I tried to break it, but did not get an error.

**Comment by wsanchez** [comment]
Well… that's actually unexpected.

OK, closing until we see this again.

**Comment by corprew** [comment]
is there something that we can do to try and repro this for you?  /zg

**Comment by wsanchez** [comment]
It's not clear to me what the cause was…  basically, what I can deduce is that in the JSON sent to the server to represent an edit to an incident, a street was being specified as a string (`"0"`) instead of the integer ('0').

So that indicates a client bug, not a server bug.

Now, the client in this case is a web client vended by the server… the JavaScript I use to generate that JSON is specifically calling `Number.parseInt` ([here](https://github.com/burningmantech/ranger-ims-server/blob/master/ims/element/incident.js#L667)) to ensure that it sends an integer and not a string.

So I think the code raising an error is correct and the client is somehow getting that wrong.  That could be explained by a bug in `Number.parseInt` as implemented by a specific browser version (eg. Safari 8 in this case).  Or my JavaScript has a bug I don't see, which is probably more likely.

The challenge is that I don't know how to cause my client to reproduce this and I think only k8 has seen it.

**Comment by corprew** [comment]
@wsanchez This is a guess that I have no way of confirming because I upgraded my macos sometime in the past several years, but looking at the data in the select form for hours, safari 8 might be having some sort of issue with Number.parseInt.

In earlier versions of Javacscript, some implementations of `Number.parseInt` assumed that a string with the leading zero was in *Octal*.

![image](https://cloud.githubusercontent.com/assets/56199/16507218/00765e40-3edd-11e6-9927-195ef678fb3b.png)

If this theory is correct, @iamk8 should only have problems setting the location to 8 or 9 o'clock, but the conversion for 10, 11, & 12 will be wrong.

If this theory is correct, you could remedy this problem by changing     
```
    return Number.parseInt(value);
```

to 
```
    return Number.parseInt(value, 10);
```

You might want to do that anyway in case someone has a older client out there, because it'll generate weird data.  https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/parseInt  and http://www.ventanazul.com/webzine/articles/issues-parseint-javascript

It looks like the *leading zero means octal is dumb* correction got put in in ECMA 2015.

meh?  best idea i've got.

**Comment by plapsley** [comment]
Henceforth I will refer to the 10 o’clock radial as 0xa.

Phil

**Comment by scottlbaker** [comment]
but 10 o’clock is 12 o’clock in octal

**Comment by hariboukis** [comment]
Nerd. 



--------------------------------
Hari Boukis
Mobile: 925-351-7772
Mobile e-mail: Hari@Boukis.com
Fax: 925-956-7013
--------------------------------
Sent from mobile phone
--------------------------------


On Jun 30, 2016, at 6:06 PM, plapsley <notifications@github.com> wrote:

Henceforth I will refer to the 10 o’clock radial as 0xa.

Phil

**Comment by wsanchez** [comment]
@corprew Dude, you rock.  Anyone who can enable me to blame JavaScript for being stupid wins in my book, especially if it means a bug wasn't my fault.

0a119c89e2dbe495ac3ec59dd74d8ea7a51b7b21
