### ISSUE TITLE
UI needs to show when there an unattached incident reports

### ISSUE THREAD

**Issue by wsanchez** [burningmantech/ranger-ims-server#718]
When we have new incident reports, they need to be attached to incidents in order for them to be useful.

If nobody is looking for them, that doesn't happen. We need a support for a UI affordance for highlighting this condition.

**Comment by srabraham** [comment]
This seems like it might in an OK state. Note that the Incident Reports page can be sorted by Attached Incident, e.g. below. Also, as of recently, unattached incident reports are called out in the "add incident report" dropdown: https://github.com/burningmantech/ranger-ims-server/issues/1319
 
<img width="288" alt="image" src="https://github.com/user-attachments/assets/7dda9110-8abd-43da-84a3-fb012a61462e">

**Comment by srabraham** [comment]
With https://github.com/burningmantech/ranger-ims-server/issues/1319 resolved (via https://github.com/burningmantech/ranger-ims-server/pull/1321), I think this might be good enough to call it done. The React client might choose a different approach, of course.
